name: ProxyTicketsBukkit-Minecats
main: de.sabbertran.proxytickets.bukkit.ProxyTicketsBukkit
version: 1.2.0
website: http://www.sabbertran.de
author: Sabbertran
maintainer: AeSix
description: ProxyTickets-Minecats Bukkit handler